import {
  Banknote,
  BriefcaseBusiness,
  Bus,
  Car,
  Coffee,
  Flower2,
  Gift,
  GraduationCap,
  HandHeart,
  PawPrint,
  Plane,
  ReceiptText,
  ShieldCheck,
  ShoppingBasket,
  Smartphone,
  Soup,
  Trophy,
  UsersRound,
  Wifi,
  Zap,
  PiggyBank,
  Tag,
  Clapperboard,
  Dumbbell,
  Home,
  Landmark,
  Laptop,
  type LucideIcon,
  ShoppingBag,
  UtensilsCrossed,
} from 'lucide-react';

import type { CategoryIconKey } from '@shared/contracts/categories';

export const categoryIcons: Record<CategoryIconKey, LucideIcon> = {
  salary: Banknote,
  freelance: Laptop,
  investment: Landmark,
  housing: Home,
  food: UtensilsCrossed,
  transport: Bus,
  shopping: ShoppingBag,
  health: Dumbbell,
  entertainment: Clapperboard,
  savings: PiggyBank,
  education: GraduationCap,
  travel: Plane,
  pets: PawPrint,
  groceries: ShoppingBasket,
  dining: Soup,
  coffee: Coffee,
  utilities: Zap,
  internet: Wifi,
  phone: Smartphone,
  insurance: ShieldCheck,
  taxes: ReceiptText,
  gifts: Gift,
  charity: HandHeart,
  family: UsersRound,
  beauty: Flower2,
  sports: Trophy,
  vehicle: Car,
  work: BriefcaseBusiness,
  other: Tag,
};

export function getCategoryIcon(key: string | null | undefined): LucideIcon {
  return key && Object.prototype.hasOwnProperty.call(categoryIcons, key)
    ? categoryIcons[key as CategoryIconKey]
    : categoryIcons.other;
}
